### PR TITLE
Python server

### LINKED ISSUE #10: Add functionality to back end
recreate the functionality of the old backend in the new python backend

### PR DESCRIPTION
**Pull request by Lewis-Kelley**
Close #10 

# Concerns I Have:
- `serverAddr` / `verifyAddr` are both `'0.0.0.0'`, which seems wrong
- we seem to have a username, `'bgoyt6'` in the `pgConString` field for
  non-local configs
- do we have access to the keys that this needs to run? that kind of
  makes testing difficult…
- I didn't change the user in the config for non-local runs, but I have no 
  way to check if that still works without running the whole server
# Unmoved Pieces:
- no verify-thing
- no audio
I did move the whole config object over, complete with the verify contents, which might be a bad idea if they're not being used?

### CODE REVIEW

**Comment by jcolemang** [comment]
- I don't think `0.0.0.0` is an issue. That address is just like `127.0.0.1` except it allows you to accept connections to the outside world. 
- We should probably recreate the databases at some point and can change it then
- Those are on the physical server. Or I guess it's a VM, but either way it isn't on our computers. I would say that we should test with the local config and can consider that good enough for PR's. Maybe moving it onto the physical server could be its own story.
- See above

**Review by jcolemang — COMMENTED** [review]
Did you change any of the client js code?

**Comment by Lewis-Kelley** [comment]
@jcolemang Not meaningfully, no. I split out some of the larger blocks of Javascript code into their own file, but that's it.

**Comment by jcolemang** [comment]
@Lewis-Kelley That's what I saw, I wanted to make sure I didn't have to try and find the changes. Thanks

**Review by jcolemang — APPROVED** [review]
I mostly scanned this as I believe this was really just meant as a rewrite of the existing backend. It would probably make sense to add another story to add some basic tests to this unless you really want to add a commit, but I think it is fine as is.

**Review by kgroble — APPROVED** [review]

**Pull request merged**
